baseURL = "https://ohadravid.github.io/"
title = "Tea and Bits"
theme = "gokarna"

languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

pygmentsStyle = "nord"

[params]
  description = "Ohad's blog"
  socialIcons = [
    {name = "twitter", url = "https://twitter.com/ohadrv"},
    {name = "github", url = "https://github.com/ohadravid"},
    {name = "email", url = "mailto:ohad.rv@gmail.com"}
  ]
  metaKeywords = ["blog", "tech", "rust"]
  showPostsOnHomePage = "recent"
  numberPostsOnHomePage = 15
  customHeadHTML = '''
    <style>
    /* Disable floating header. */

    #content {
        margin-top: 0 !important;
    }

    .header {
        position: relative !important;
    }

    .header-shadow {
        box-shadow: none !important;
    }

    [data-theme="dark"] {
      --blockquote-color: rgb(210, 210, 210);
    }
    
    [data-theme="light"] {
      --blockquote-color: rgb(59, 58, 57);
    }
    
    blockquote {
      color: var(--blockquote-color);
    }
    </style>
    <script>
    const originalSetThemeByUserPref = setThemeByUserPref;

    // Override the default function and add a class to root with the current theme.
    setThemeByUserPref = function () {
        originalSetThemeByUserPref();

        onDisabledChange(darkThemeCss.disabled);

        const observer = new MutationObserver((mutations) => {
          for (const mutation of mutations) {
            if (mutation.type === "attributes" && mutation.attributeName === "disabled") {
              onDisabledChange(darkThemeCss.disabled);
            }
          }
        });

        observer.observe(darkThemeCss, {
          attributes: true,
          attributeFilter: ["disabled"],
        });
        
        function onDisabledChange(isDisabled) {
          if (isDisabled) {
            document.documentElement.setAttribute("data-theme", "light");
          } else {
            document.documentElement.setAttribute("data-theme", "dark");
          }
        }
    };
    </script>
    <script defer data-domain="ohadravid.github.io" src="https://plausible.io/js/script.js"></script>
    
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  '''
[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/ohadravid"
    weight = 5

  # TODO: make this work for posts.
  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 6

[params.hidden]
  tags = ["no-description"]
  tagsPostDescription = ["no-description"]

# To avoid listing a post, use 
# ```
# _build: 
#  list: never
# ```
# in the front matter of the post.

# To customize the text in the card without displaying a description, 
# set `summary` in the front matter of the post.

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false